### ISSUE TITLE
Handle L2P(Y)

### ISSUE THREAD

**Issue by ljbade** [swift-nav/gnss-converters#10]
Since most CORS stations only provide L2P(Y) observations, and not L2C we need a way to use them.

After chatting with @anth-cole it seems the correct way to handle this is:
For message type 1004/1012 use the manufacturer lookup table to align everything to L2C with regards to the 1/4 cycle carrier phase offset.

For MSM everything should already be aligned to L2P(Y). So a fixed conversion to L2C will be all that is needed.

/cc @mookerji @mfine

**Comment by mookerji** [comment]
Done!
