### ISSUE TITLE
Use message type 1013 for GPS weeknumber

### ISSUE THREAD

**Issue by ljbade** [swift-nav/gnss-converters#6]
Using message type 1013, might avoid the need for calculating the GPS week number for SBP from the local computer's clock.

See https://github.com/swift-nav/librtcm/pull/2#issuecomment-200324020

/cc @mfine

**Comment by mfine** [comment]
@ljbade you were thinking of deriving WN off MJD? Having some troubles currently pulling directly from the PRS mountpoint, but not seeing 1013 message in the source table - not sure if it's actually being sent:

```
STR;PRS;PRS v30;RTCM30;1004(1),1005(10),1007(30),1012(1),1030(30),1031(30),1032(10),1033(60);2;GNSS;SwiftNav Net;USA;50.09;8.66;1;1;GNSMART;none;B;Y;4800;source
```

**Comment by ljbade** [comment]
I might play with the Geo++ config, you can specify which messages to send so I will see if it can be turned on.

**Comment by mfine** [comment]
Week number can now be stored and updated: https://github.com/swift-nav/gnss-converters/pull/16.

**Comment by ljbade** [comment]
Ah sweet, @mookerji if you get time before me, can you try enabling 1013 in Geo++

**Comment by mfine** [comment]
Done.
