### ISSUE TITLE
Track the station reference ID

### ISSUE THREAD

**Issue by ljbade** [swift-nav/gnss-converters#7]
It is possible for two stations' observations to be sent in one stream by using different Reference Station IDs.

We should check and latch the first ID we see. Then report an error/warning if we see a different ID, and drop those observations.

/cc @mfine

**Comment by mfine** [comment]
The idea here would be to filter a stream down to a single source of `Reference Station ID's` based on the first `Reference Station ID` seen? Is this necessary? Currently, piksi doesn't track observations per their source outside of the `senderId` - a) would the extra observations be harmful? b) is the non-deterministic first source seen going to be a good approach?

**Comment by ljbade** [comment]
Oh so currently the station ID is mapped to a Piksi senderId?

If thats the case then yeah I think we could rely on Piksi (or navengine) to filer by that.

**Comment by mfine** [comment]
@ljbade it's not, but it might be a good idea to set it to that. @mookerji what do you think?

**Comment by mfine** [comment]
@fnoble hey, you have any thoughts about pulling in RTCM's Station ID into SBP's Sender ID? Station ID is 12 bits, Sender ID is 16 bits.

**Comment by mfine** [comment]
A downside here could be senderId clashes - we don't control the Station ID namespace, and it could conflict with existing devices. Something chumpy we could do would be to turn on those 4 top bits for the station id's to avoid collisions. That would start numbering station id's from a base of 0xF000 or 61440.
