### ISSUE TITLE
Be careful of SBAS IDs

### ISSUE THREAD

**Issue by ljbade** [swift-nav/gnss-converters#9]
In RTCM any GPS IDs >32 are reserved, except for 40-58 which are used for SBAS.

We need to filter (and warn?) about any IDs outside these ranges, and assign the correct SBP system/constellation ID numbers to the SBAS IDs. Or drop those observations.

/cc @mfine

**Comment by mfine** [comment]
@ljbade how about we filter them out to start with? Will add a patch for that.

**Comment by ljbade** [comment]
Yep that sounds like a reasonable approach.
